(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib._490772997 = function() {
	this.initialize(img._490772997);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,612,93);


(lib.skis = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC9900").s().p("ABAEOQgEgIgCg1IAAgkIAAgQIgBgjIgBgcIAAgnQgEAFgEgEIgCgEQgCgGAGgLIAEgGIACgCIgChPIgBglIgBglQgDgbAAglIABgfQAGgjAHgKQAGgIAGAKQAFAGAEAPIAEAMQAHASgBAtIgBAeIAAAvIAAAjIgBBOQAIAIADAMIAAAKQgCAHgFgFIgFgHIABA3IABA3QACAmgEApQgCAVgDANgAhdEOIgJgBQgBgKADgVIAqi6IgDACIgCACQgCgKAHgIIAFgEIADgCIAZh1IAZh2QADgMAHgMIAFgHIACgCQANgQAGALIADAKIAAAEQADAOgCAMIgBAHIgBACIg3DnQAEADACAHIAAAGQgBAJgEgCQgCAAgCgDIgoCYQgHAagJATQgFAKgDAEg");
	this.shape.setTransform(10.3,27.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,20.7,54.1);


(lib.skieur = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgLAVIgDgCIgCgEIgBgEIgCAAIgBgCIAAgBQgGgDgJgFIgSgLIgIgJIAAgGIAAgBIAOAMQAQAMAKADIAAgBIAAgBIAEACIACgDQADgDAGABIAagCQAegDAMgFIAAAFIgBAMIgBAHIgCAGIgEAFQgDACgDABIgCAAIgHgCQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAQgCgCgDAEQgDADgHACIgIABQgMAAgNgHg");
	this.shape.setTransform(54.6,8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#26B2E3").s().p("AHpFPQgVgEgJAAIgJADQgLACgHgBIkQgvIhBgLIhVgPIiUgaIASgTIA0AIIAIgHIBqAQIAAgBIACgBIACgCQAAAAAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgGgLQgGgLgBgFIgLgfQgDgFgCgJQgDgRAHgSQgHAHgOAFQgXAJgdgDIgLgBQgMgCgNgHQgcgOgMgdIgCgBQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAIgEACQgFABgDgCIgBAAQgBAAAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgCABIgKAAIgEgBQgFgDgGgHIkWBVIhLAXIgBABIACABIAEABQAEABgDAEIgBACIgDACIgEABQgDAAABgFIgBgBIgBADIgCACQgDABgBgEIgDgFQgCgHAEgGIACgCQABAAAAAAQABAAAAAAQABAAAAABQAAAAABABIAAACQAAABAAAAQAAAAABAAQABAAAAAAQABAAABgBIFfhrIgBgCIACgOIgCgHIgGgKQgGgJgEgFIgGgJQgHgLgCgEIgBgCQgCgEgGgFIgCgDQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAgBABAAIgBgBQgBAAAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAIgDAAQgCgCAAgEIAAgBQAAAAgBAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgBgDQAAgDABgCIAAgBIgCAAIgCAAQgCgBADgGIACgFQABgGgBgBIgBgBQAAgDACgCIACgEQAAgEgBgCIgCgCQgBgCADgEQABgEAEgFQAJgKAPgHQAAAAABAAQAAAAABgBQAAAAABAAQAAgBABAAQAFgEACgFIADgFQAEgEAGgCIADgCQAHgCAGgFQAOgJACgKIADgFQACgEADgBIAEgCIAEgEIADgDIAFgDQAEgCAAgCIAJgMIgCAAIAAgIQABgKAFgMQABgFAEgHIADgEQAGgIAJgBIACgCQABAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAIAEgIQAEgIAEgCIAEgCIAEgDIAJAJIARAMQAJAGAHACIAAACIAAABIADAAIABAFIACADIADADQASAJAOgDQAHgCAEgEQACgDADABQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAIABIACAAQADAAACgCIgEADIgCAIIADAAQAEgBACgCIAEgBQAEAAADAFIADACQADACAEAAIACACIAGAFIACABIAEABIALAAIAIABQAMACAXAJIAGACQAFADACACIAEADQAFACAEAAIAJABQAJACAEAEIABgBIAGgBQAJgBAOAGIAEABIAIAGQAMAKgDAOQgCAGgEAGQgHAMgMAAIgDABQgFABgCgCIgBgBIgEABIgEAAIhmB8IgBACQgBADAGgDIADgBQACgBAAAGIgCAGQgDAEgCgFIgBgBQgBAAAAAAQAAAAAAAAQAAABAAABQAAABAAABIABABQgBACgEgBIgDgBIgCgCQgGgEgBgGIABgFQACgDACAFIADABIABAAQACgBABgDIBmh+IAAgBQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIgFgEQgFgFgIgDIAAADIgMACQgNACgEgEIgDAAIgCACIgDAAIgKAAIgQgCIgJgBQgJgBgCABIgHgDIgBgBIgDgCQgEgCgDADIgDADQgEABgGgGIgCgCQAAAAgBABQAAAAgBAAQAAAAAAABQAAAAAAABIgBAAQgCAAgFgEQgCgDgDACQgEACACATIABAFIABANQAAAUgFAMIgCAFQgBAGABADIACAHQABAIgEAEIgCAEQgCAFACADIABAEQABAFgBAGIABAFIADAGIABABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAIACANIATAcIADAAQAEAAADACQAJAFADAOIABAHIAWAVQAXAZAKAPIAEAEQAFAEACAAIABAAIACABQADAEAEAOIACANQADAOAFAJIAHAPQAGAQAAALIAAABIAFADQAKAHAfAOIAGAEQAGAFgBAFIDXAjIADAAQAEABAKgCIAAABIgCADIAHABIARAAQAZABAMgEQgDAIgIAIQgPAPgVAAIgHgBgABBj+IABgMIAAgGQAAALgBALIgCAEIACgIgAgRkCIAAAAIAAABQgLgDgQgMIgOgMQAAgJAFgLIAEgHQAMgRAZgFIAGgCIAPAAQAZADARATIADAFIAGANQAFAMABALQgNAFgdAEIgbABQgGgBgCADIgCADIgEgBg");
	this.shape_1.setTransform(54.3,33.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,108.6,67.2);


(lib.neige = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BAFCFF").s().p("Egi5AErQgNgHgGgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAGAAACgDQAOABANAJQANAJAFAOQAFAOgEAPQgEAPgMAKQgLAJgQACIgGAAQgMAAgKgFgEg1LAEgQgNgFgJgLQgIgMgBgOQAAgHABgHQAEgOAHgJQALgMARAAQAHAAABgDQANABAMAIQAMAIAGANQAFANgCAOQgDAOgJAKQgKAKgOAEIgMABQgHAAgIgCgA7tEDQgNgHgGgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAGAAACgDQAOABANAJQANAJAFAOQAFAOgEAPQgEAPgMAKQgLAJgQACIgGAAQgMAAgKgFgEAw1AB3QgMgHgHgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAHAAABgDQAPABANAJQAMAJAFAOQAFAOgEAPQgEAPgLAKQgLAJgQACIgHAAQgLAAgLgFgAo0BFQgMgHgHgNQgEgIgBgLQgBgRAGgLQAFgJAKgHQAKgGALAAQAHAAABgDQAPABANAJQAMAJAFANQAFAOgEAPQgEAPgLAKQgLAJgQACIgHAAQgLAAgLgFgEAnxAAdQgMgHgHgNQgEgIgBgKQgBgRAGgLQAFgKAKgHQAKgGALAAQAHAAABgDQAPABANAJQAMAJAFAOQAFAOgEAPQgEAOgLAKQgLAJgQACIgHAAQgLAAgLgFgEg3NgAKQgNgHgGgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAGAAACgDQAOABANAJQANAJAFAOQAFAOgEAPQgEAPgMAKQgLAJgQACIgGAAQgMAAgKgFgA/dhQQgNgHgGgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAGAAACgDQAOABANAJQANAJAFAOQAFAOgEAPQgEAPgMAKQgLAJgQACIgGAAQgMAAgKgFgA2ahuQgMgHgHgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAHAAABgDQAPABANAJQAMAJAFAOQAFAOgEAPQgEAPgLAKQgLAJgQACIgHAAQgLAAgLgFgAZji0QgMgHgHgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAHAAABgDQAPABANAJQAMAJAFAOQAFAOgEAPQgEAPgLAKQgLAJgQACIgHAAQgLAAgLgFgEgthgC+QgNgHgGgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAGAAACgDQAOABANAJQANAJAFAOQAFAOgEAPQgEAPgMAKQgLAJgQACIgGAAQgMAAgKgFgEA2dgDSQgMgHgHgNQgEgIgBgLQgBgRAGgLQAFgKAKgHQAKgGALAAQAHAAABgDQAPABANAJQAMAJAFAOQAFAOgEAPQgEAPgLAKQgLAJgQACIgHAAQgLAAgLgFg");
	this.shape.setTransform(355.8,30.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,711.7,60.8);


(lib.montagne = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.instance = new lib._490772997();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.914,0.914);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,559.4,85);


(lib.lieu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC9900").s().p("AgNA0IAHgPIADgMIACgNIABgMQAAgLgDgMQgCgLgIgRIALAAQAHAMAEANQAFANAAANQAAAKgEANQgEAPgIAOg");
	this.shape.setTransform(141.6,14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC9900").s().p("AgRAfQgJgJAAgWQAAgUAJgKQAIgJALAAQAKAAAFAFQAGAFACAJIgPACQAAgFgCgCQgDgCgEAAQgDAAgEAEQgDAFAAANQAFgGAHAAQAKAAAGAHQAIAGAAALQgBAMgHAIQgHAHgLAAQgLAAgHgJgAgGACQgDAEAAAGQABAIADAEQADAEADAAQAFAAACgEQADgDAAgHQAAgIgDgEQgCgCgFAAQgDAAgEACg");
	this.shape_1.setTransform(136.9,13);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CC9900").s().p("AgSAfQgHgJgBgWQABgUAHgKQAJgJAMAAQAIAAAGAFQAGAFACAJIgPACQgBgFgCgCQgCgCgEAAQgDAAgDAEQgEAFgBANQAGgGAIAAQAJAAAGAHQAIAGgBALQAAAMgHAIQgHAHgLAAQgLAAgIgJgAgFACQgEAEAAAGQABAIADAEQADAEADAAQAFAAACgEQADgDABgHQgBgIgDgEQgDgCgEAAQgDAAgDACg");
	this.shape_2.setTransform(130.8,13);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC9900").s().p("AADA0QgHgNgEgNQgFgOAAgMQAAgPAGgNQAEgMAHgLIAKAAQgIARgCALQgDAMAAALQAAAJACAJQABAKADAIIAHAQg");
	this.shape_3.setTransform(125.9,14);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgmA7QgOgMgCgXIAagDQADAOAHAGQAHAGAMAAQANAAAHgFQAHgGAAgIQAAgEgDgDQgDgEgHgCIgVgHQgWgFgJgHQgMgLAAgQQAAgLAFgJQAGgJALgFQALgEAQgBQAZAAANAMQANALAAATIgbABQgCgLgGgEQgGgEgKAAQgMgBgHAGQgEADAAAFQAAAEAEAEQAFAFATAEQAUAFAKAFQAJAFAGAIQAFAIAAANQAAAMgGALQgHAJgMAGQgMAEgRAAQgZABgOgMg");
	this.shape_4.setTransform(116.2,12.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgzBEIAAiHIBkAAIAAAXIhIAAIAAAeIBDAAIAAAWIhDAAIAAAlIBLAAIAAAXg");
	this.shape_5.setTransform(103.9,12.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgvBDIAAiGIAcAAIAABwIBDAAIAAAWg");
	this.shape_6.setTransform(92,12.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgfA9QgQgJgIgQQgIgRAAgTQAAgUAJgRQAJgRARgJQANgGATgBQAZAAAOAMQAPAKAEATIgcAFQgCgKgIgGQgIgGgMAAQgRAAgLALQgKAMAAAWQAAAYAKAMQALAMARAAQAIAAAJgEQAJgDAGgFIAAgRIggAAIAAgWIA8AAIAAA2QgJAHgQAHQgRAGgRAAQgUABgQgKg");
	this.shape_7.setTransform(78.2,12.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAbBEIg3hYIAABYIgZAAIAAiHIAbAAIA3BaIAAhaIAZAAIAACHg");
	this.shape_8.setTransform(64,12.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAmBEIgMgfIg1AAIgLAfIgdAAIA1iHIAcAAIA2CHgAgSAOIAkAAIgSgyg");
	this.shape_9.setTransform(50.3,12.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgmA7QgOgMgCgXIAagDQADAOAHAGQAHAGAMAAQANAAAHgFQAHgGAAgIQAAgEgDgDQgDgEgHgCIgVgHQgWgFgJgHQgMgLAAgQQAAgLAFgJQAGgJALgFQALgEAQgBQAZAAANAMQANALAAATIgbABQgCgLgGgEQgGgEgKAAQgMgBgHAGQgEADAAAFQAAAEAEAEQAFAFATAEQAUAFAKAFQAJAFAGAIQAFAIAAANQAAAMgGALQgHAJgMAGQgMAEgRAAQgZABgOgMg");
	this.shape_10.setTransform(32.5,12.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgzBEIAAiHIBkAAIAAAXIhIAAIAAAeIBDAAIAAAWIhDAAIAAAlIBLAAIAAAXg");
	this.shape_11.setTransform(20.2,12.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgvBDIAAiGIAcAAIAABwIBDAAIAAAWg");
	this.shape_12.setTransform(8.3,12.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,145.7,25.3);


(lib.leitmotive = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#26B2E3").s().p("AgJA2IAAgVIATAAIAAAVgAgFAaIgFg1IAAgaIAVAAIAAAaIgFA1g");
	this.shape.setTransform(204.6,10.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgcAbQgHgKAAgRQAAgSAKgLQAKgLAPAAQARAAAKAMQAKALgBAXIgyAAQAAAJAFAFQAEAFAGAAQAFAAAEgDQADgCACgGIAUADQgEAMgIAGQgJAGgNAAQgTAAgKgOgAgKgTQgEAFAAAIIAeAAQAAgJgFgEQgEgFgHAAQgFAAgFAFg");
	this.shape_1.setTransform(193.8,11.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgbAsQgKgLAAgTQAAgTAKgKQAJgLAOAAQAMAAAKALIAAgnIAUAAIAABrIgTAAIAAgMQgFAHgGADQgGAEgHAAQgMAAgKgLgAgLgEQgFAFAAALQAAANADAFQAGAIAHAAQAIAAAEgGQAGgGAAgMQgBgNgEgFQgFgGgIAAQgGAAgFAGg");
	this.shape_2.setTransform(184.9,10.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgXAlQgGgEgDgGQgCgHAAgKIAAgxIAUAAIAAAkQAAAQABADQABAEADACQADACAFAAQAEAAAEgDQAFgDABgEQACgEAAgQIAAghIAUAAIAABNIgTAAIAAgLQgEAGgHADQgGAEgIAAQgHAAgHgDg");
	this.shape_3.setTransform(175.9,11.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgCAzQgFgCgCgCQgCgDgBgFQgBgEAAgLIAAghIgJAAIAAgQIAJAAIAAgQIAUgLIAAAbIAOAAIAAAQIgOAAIAAAeIABALQAAABAAAAQAAABAAAAQAAAAABAAQAAABAAAAIAEABIAIgCIACAQQgHAEgJAAQgGgBgDgCg");
	this.shape_4.setTransform(168.9,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgJA2IAAhNIATAAIAABNgAgJgiIAAgTIATAAIAAATg");
	this.shape_5.setTransform(164.3,10.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgCAzQgFgCgCgCQgCgDgBgFQgBgEAAgLIAAghIgJAAIAAgQIAJAAIAAgQIAUgLIAAAbIAOAAIAAAQIgOAAIAAAeIABALQAAABAAAAQAAABAAAAQAAAAABAAQAAABAAAAIAEABIAIgCIACAQQgHAEgJAAQgGgBgDgCg");
	this.shape_6.setTransform(159.7,10.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgCAzQgFgCgCgCQgCgDgBgFQgBgEAAgLIAAghIgJAAIAAgQIAJAAIAAgQIAUgLIAAAbIAOAAIAAAQIgOAAIAAAeIABALQAAABAAAAQAAABAAAAQAAAAABAAQAAABAAAAIAEABIAIgCIACAQQgHAEgJAAQgGgBgDgCg");
	this.shape_7.setTransform(154.7,10.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAeA2IgJgZIgqAAIgJAZIgXAAIAqhrIAWAAIArBrgAgOALIAcAAIgOgng");
	this.shape_8.setTransform(146.7,10.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgJA2IAAhrIATAAIAABrg");
	this.shape_9.setTransform(135.7,10.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgTAkQgKgFgFgJQgFgKAAgMQAAgKAFgKQAFgKAJgFQAJgFALAAQARAAAMAMQALALAAARQAAARgLAMQgMAMgRAAQgKAAgJgFgAgNgRQgFAGAAALQAAALAFAHQAGAGAHAAQAIAAAFgGQAGgHAAgLQAAgLgGgGQgFgGgIAAQgHAAgGAGg");
	this.shape_10.setTransform(129.1,11.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgTAkQgKgFgFgJQgFgKAAgMQAAgKAFgKQAFgKAJgFQAJgFALAAQARAAAMAMQALALAAARQAAARgLAMQgMAMgRAAQgKAAgJgFgAgNgRQgFAGAAALQAAALAFAHQAGAGAHAAQAIAAAFgGQAGgHAAgLQAAgLgGgGQgFgGgIAAQgHAAgGAGg");
	this.shape_11.setTransform(119.9,11.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AggApQgOgPAAgZQAAgaAOgPQAOgPAWAAQATAAANAMQAHAHAEANIgWAFQgCgJgGgEQgGgFgIAAQgLAAgIAIQgHAJAAATQAAATAHAJQAHAJALAAQAJAAAGgFQAGgGADgMIAVAHQgFARgLAJQgLAJgSAAQgUAAgOgPg");
	this.shape_12.setTransform(109.8,10.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#26B2E3").s().p("AAUAsQgHAFgHADQgHADgKAAQgUAAgKgLQgIgJAAgLQAAgLAGgIQAHgHAMgGQgGgHgCgFQgDgHAAgFQAAgJAIgIQAHgGAPAAQANAAAIAHQAHAHAAAKQAAAHgDAGQgEAFgMAIIAPASQACgEACgIIATAFIgFAOIgEAIIAJAHIAIAFIgNAQQgJgFgIgHgAgYAMQgEAGAAAFQAAAGAFAFQAEAEAHAAQAFAAAFgCQADgCAGgFIgUgZQgIADgDAFgAgMgmQgDACAAADQAAAEAFAFIAFAHIAFgFQAFgFAAgEQAAgEgDgDQgCgDgFAAQgFAAgCADg");
	this.shape_13.setTransform(95.1,10.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgcAbQgHgKAAgRQAAgSAKgLQAKgLAPAAQARAAAKAMQAKALgBAXIgyAAQAAAJAFAFQAEAFAGAAQAFAAAEgDQADgCACgGIAUADQgEAMgIAGQgJAGgNAAQgTAAgKgOgAgKgTQgEAFAAAIIAeAAQAAgJgFgEQgEgFgHAAQgFAAgFAFg");
	this.shape_14.setTransform(81.1,11.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgbAsQgKgLAAgTQAAgTAKgKQAJgLAOAAQAMAAAKALIAAgnIAUAAIAABrIgTAAIAAgMQgFAHgGADQgGAEgHAAQgNAAgJgLgAgLgEQgFAFAAALQAAANADAFQAGAIAIAAQAGAAAFgGQAFgGABgMQAAgNgFgFQgFgGgHAAQgHAAgFAGg");
	this.shape_15.setTransform(72.2,10.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgJA2IAAhNIATAAIAABNgAgJgiIAAgTIATAAIAAATg");
	this.shape_16.setTransform(65.8,10.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAWA2IgPgYIgLgPQgDgEgDgBQgEgBgHAAIgFAAIAAAtIgVAAIAAhrIAtAAQARAAAHADQAIADAFAIQAFAHAAAJQAAANgIAHQgHAHgOACQAHAEAFAFQAEAFAIANIANAVgAgagHIAQAAQAPAAAEgCQAEgBACgDQACgDAAgFQAAgGgDgDQgDgDgFgBIgPAAIgRAAg");
	this.shape_17.setTransform(58.7,10.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#26B2E3").s().p("AgKAOQAGgCADgEQABgEAAgFIgIAAIAAgUIATAAIAAAOQAAAIgBAGQgCAFgEAEQgEAEgGACg");
	this.shape_18.setTransform(46.5,15.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgZAeQgLgLAAgTQAAgSALgLQAKgLAQAAQAOAAAJAGQAIAGAEANIgUAEQgBgGgEgEQgEgDgGAAQgGAAgFAGQgEAFAAAMQAAANAEAGQAFAGAHAAQAGAAADgEQAEgDACgIIAUADQgDAOgJAHQgJAIgPAAQgQAAgKgLg");
	this.shape_19.setTransform(40.4,11.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgJA2IAAhNIATAAIAABNgAgJgiIAAgTIATAAIAAATg");
	this.shape_20.setTransform(34.1,10.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgXAiQgJgGgDgLIAUgEQACAGAEAEQAEADAGAAQAIAAAEgDQADgCAAgEQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAAAgBgBQgBgBgGgBQgXgGgHgEQgJgGAAgLQAAgKAIgHQAIgHAQAAQAPAAAIAFQAIAGADAKIgUADQgBgEgDgDQgEgCgGAAQgHAAgEACQAAABgBAAQAAAAgBABQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAABQAAAAABAAQAAABABAAQADACAPAEQAQAEAHAFQAGAFAAAJQAAALgJAIQgIAIgSAAQgPAAgJgHg");
	this.shape_21.setTransform(27.6,11.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgXAlQgGgEgDgGQgCgHAAgKIAAgxIAUAAIAAAkQAAAQABADQABAEADACQADACAFAAQAEAAAEgDQAFgDABgEQACgEAAgQIAAghIAUAAIAABNIgTAAIAAgLQgEAGgHADQgGAEgIAAQgHAAgHgDg");
	this.shape_22.setTransform(19.1,11.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AAgA2IAAhUIgWBUIgUAAIgUhUIAABUIgVAAIAAhrIAgAAIATBJIAThJIAhAAIAABrg");
	this.shape_23.setTransform(8.3,10.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,209.9,20.8);


(lib.foule = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#266CA1").s().p("ANwE5IATgRIAEgEQAEgGADgGQAOgbgDgkQADgYgBgeQgDg8gUgbQAAgFgDgFQgGgKgJABQgGABgLgCQgWgDgXgNQgXAkgLADIgGAJQgEALAGAJIANAgQAOAlgBAVIAAAZQADAYAJAhIAGAQIAFAQIgiAAQgIgIgFgIQgEgIgCgIIAAgCQABgFgBgDQgDgFgJANIgCACIgGAIIgDAIQgCAIAEAHIhwAAIABgPIAAgQIAAglQgChJgLgXIgDgIQgDgMADgSQgBgHgCgEQgGgKgIAIQABAAAAABQAAAAAAAAQgBABAAAAQgBABgBAAQgIADgbAAIgGAAQgHACgBAMIgCAKQgGASgWArIgNAkQgHAdAFAcIAEAQIAGAOIioACIAAgQIABgQIAAgcQgBhDgPgjQgHgaAAgXQABgHgCgJQgEgSgRgKIgVgSQgXgXgHgQQgHgXgPgLQgEgJAAgOQgBgcATgZIAYgoQAIgNgFgPQABgJAEgJQAGgSALABIAOACQAOAFABAOIAAAPQgEARgVAJIgMAiQgMAlgBARIgBAEQAAAFADAGQAKASArAVIARAJQASAKAHAOIACAEQAFACAKgCIAKgGQAKgGADAAQADgEABgIQADgOgJgRQgGgOACgRQAEgiArgMIAKACQANACAIAIQAaAXgWA6IgJAOQgHAQAFAIIATANQAWALAJgLIAGgGQAOgEAtAJQABAAAAgBQABAAAAAAQABgBAAAAQAAgBAAgBQADgFgIgJQgJgXgJgeQgUg+AAgkQgngpgJgOIABgBQAEABAMALQAMAFgKgJIgFgHQgFgHABAAIAAgCQACAAALAJQALAGgHgIQgGgIgEgJIABgEQACgBAHANIALAIQAIAEgJgQIgCgHQgCgHADgBIAGAIIAIANIAKAPQAKANADgRIAEgLQAEgLACABQAAAYgDAJIgEARQgCAVAIATIACgMIAOgCQAPgBAIALIAAAlIAVA/QAUBBgEAUIACAJQADAKAFADIAbAAIAHgDQAGgHAAgNQgGgaABgbQAEg1ArgFIADggQAGghAIgLQgBgQAAgQQgBggAEAAIAKgCQAMgBAIADIAHgUQAHgUABAAIAEAEQACAKgJAiIAEAMQADAOgHAKQgFABgFAIQgLAPgCAfIAAA5QABAEAEADQAPAMAyAHIAUgFQAYgBAVARQAFACADgEQAEgIgPgZQgCACgDgQQgIgfgJhaIgIgMQgIgOADgMIAEgKQAJgJAWABIADgOIABgGIAEgBQABABABAGIABAbQABAcAEgPIAEgJQAEgGACAPIABAKQgCANgOAMIgBAQQAAATAKAUIAKgRQAOgRAYAEIAJABQAJADAHAFQAYARgNAoIgLASQgHAVAQANIADAEQAEADAEgHQgDgKADgNQAGgaAbgKIANAAQAPACAQASIAAhqQgCgFgGgHQgNgOgWgMQgGgEgEgFQgKgKAEgIIACgCQADAAAKAMIAFADQAEgBgCgTIgBgBIgHgMQgHgPACgGIAFAEQAGAEAEAHIAEABQAEgBgGgHQgGgIgGgBIAEgDQAEgEAGACIADgCQAEAAAJADIAOAOIAFADIAAI2Ij3AAgABFE4IAAgMIAAgEQACgJAEgCIABgFQAGhEgIgZQAAgGgCgDQgEgFgJAWIgEAdQgJAggRAYIgDACIgCAGIgCAIIgCAPIgUABIAAgQIAAgQIAAgUQAEg6ARgdQABgEgBgDQgCgHgJAKIgNAWQgQAhgLAwIAAAnIikAAIAAgoQgGgMgGgRQgNggABgWQABgEgDgEQgFgJgTgBIgqAAIABARQgBAXgKAWIgFAMQgDAOADAWIABALIALAIQAKAKAAADIiEAAQAGgGADgKIAAAAQAEgIAAgIQAAgMgFgMQgIgSgHgaQgQg1AAgoQAAgHgCgFQgDgIgJAOIgFALQgGANgFATQgLA0AGBIIABAQQAAAIACAHIibAAIAEgPIACgQIAAgNQAAg0gZgwQgEgGgEgCQgHgEAAATQgFAkgJAFIgDACQgDAEgCAIQgEASAGAhIACAQIAEAQIkoAAIABgQIABgQIgBgKQgBgugNgPQgggugIgRQgBgHgKABIgIAAQgGAAgEgGQgCgEgDgCQgFgDgBAMQAAAtgJAHIgKAQQgIAUALAPIAQAoIAFAQQADAMgCAEIhKAAIAAjRIABjJIAAgGIAIgBQAJABAJAEQAZAMABApIgBAVQgFAagYAYIgCAIQADAIAPgBIALAAQALgDAAgGIAGgMQAJgNAKgDQAmgfAEgFIAHgGQAGgJAAgKIAChkIAAgFQgCgEgJADQgIABgggYQAAgEACgBQAFgEAOAJIACAAQACABADgBIADABQADgBAAgHIADgUIADgHQAEgFADANIACAOIADgCQADgBABAEIADgBQAEgCADAEIADAHQADAKABAKIAGBUQAEgJAHgIQARgRAXAAIAUADQAVAKAFAiIAAAVQgEAYgLAPIgIAHQgJAHADAIIgBAIQACAJALgBIARAAQASgFABgLQAAgFAEgHQAGgOATgJIAPgXQAPgXAFgDQAEgDAFgGQAJgMACgRQAEgLAEgQQAGgggDgbQgCgTgIgNIgBgCQgEgGgCgJQgFgSAEgMIAFADQAGAHABAQIAJADQALgBADgSIAAggIABgIIABgCQABgDABAFQABAFABANIAAAIIADAKQADAGAHgOIACgEIALgTIAHgDQAEgBgIAQIgJAXQgBAIAKgLIAKgNIABgBQALgNACAFIABAGIgBADQgCAGgHAEIgKAKIAAAEQAAADAGgEIAIgFQAIgFADADIgZAXIgKANIgBABQgKANgCAGIgCAIQgCAKACALIAAAZQgCAfgFAaQAVghAUgUQACgBABgEQADgJgCgTQAAgLABgJQADgVAIAEIADgEIAEgDIACgCQAAgDACgCQAEgDACAKIAAAAIAGgEIADgDQADgBAAAIIgBAFIgHAHQgHAJACAIQACABAIgLQADgEAFgDQAJgHADAEIgDADQgFAEgEAIIgFAGQgFAJAAAGQgCATAHgDIALgJQALgIACADIgLAQQgOARgLACIgJACQgLAGgLAcIgHAOQgIATgEAZIAAAJQABAKAEAAIAPAOQAQARABAOIAFAAQAFgDAEgHQAMgYAMgIQACgBACgEQAFgHgDgNQAHggAKgKQAHgIACgjQACgCAAgEQgBgHgKgJQgGgMgBgUIAFgBQAFACABAJQADgBACgDQAFgGgCgNIAAgNIAAgIQAAgHACgBIADABQABABABAGIACAYQACgGADgDQAGgGADAMIAHABQAIACgCAGIAAAPQgBASgLAKIgCAFQgDAGACAJQgBAwABABIAWgDQAYAAAIANIAFAGQAFAKABAKIAAA2QACADgCAEQgEAGgQADIAAAPIAAAIQABAHAJAAQAPAFALgHQABgCAEgDQAIgEAOgBQAEAAADgDQAFgHgGgTIgOgjQgNgqAAgdQAAgGgFgJQgIgSgZgQIgBgEQABgCAIAFQgOgSAEgKIABgBQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAABABIADAEQADAFACAGIABgKQAAgMADgBIABgEQADABAGAVQAFgBAAgKIADgHQAEgDACARIAEAOQAEAMAHgGIAGgDQAIgCAFADIgGAGQgGAGgBAHIgCAGQgCAIACAJIADAQQAEATAHAJIAPAlQAPAqADAaQADgBAEgDQAHgEABgJQAEgMAJgNQASgaAWgFQACgdgGgMIAAgFQgCgFgHgCQgGgEgEgGQgLgMACgLQACgKAFgEQAEgBgDgGQgEgHgCgIQgEgQAIgGIACABQABAFAAAKQAGAXACgCQAEgFAFAEIADgBQAFgBABABIACgBQADgBACACIAGgBIADAAQAEACgBANIgDAUIABALQABALAFAIQAUBhgDAIIABAIQgBAKgMAKIgIAGQgIALgDAbIAJADQAKAAAIgUQABgFAFgMQAKgYAWgfQAIgKgBgHIAIgVQAMgcAWggIADgLQABgMgIgDQgDADAAgeIAEgBQADgBACAIQAIAAAAgKIAAgLQADgJADAMQAEAPABgLIADgKQADgGABATQAAALACgHIADgGQADgEAAAMQAAAHADgDIAGgFQAEAAgKAVIgJAKQgIAMgCAHIgPAsQgQAtgGAIIgEAPQgGARgPAPIgCAWQADAVAcAAIArgHQAqgOAAgiQgFgLgDgQQgHgeAMgWIASgSQAYgNAhAUIAFAGQAEAIACAJQAGAegbAjIgBAGQgBAGACAGQAIATApADQAEAAAIgFQAQgJATgdQAFgFAFgIQAKgRACgPQANgpgDgXQACgEgCgFQgCgLgLgDQgXgQgDgJIAAgEQAEgDAWAMIAKAAQAIgDABgOIAEgMQAEgNACgBIADAAQADAGgDAeIAJAEQAJAHgBAIIAAAJQgBAKgGAEQAKBGgEALIABAJQgBAMgLAKIACADQACACAFAAIAYgIQAXgMgBgKQADgIgGgIQgEgRgBgUQgCgnAPgPIAWgMQAbgJAUAXIAFAIQAFAJADAKQAGAhgeAfIgCAEQgBAGACAFQAHASAoALIAbALQAdARAFAfIAFAQQAEAWgCAdIAFAGQAGAIAFAOQALAkABA8IAAAQIAAAQIgVAAIgCgQIgEgQIgHgeQgRhAgRgIQgFgEgDAAQgJAAADATIgFAEQgGAGgDAIQgKAaAMArIADAJIAAAHIAAAQIgqAAIh9AAg");
	this.shape.setTransform(112.7,31.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,225.4,62.6);


(lib.bouton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(Math.round(Math.random()*10));
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(113));

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAoIAAg5IAJAAIAAA5gAgEgcIAAgKIAJAAIAAAKg");
	this.shape.setTransform(75,10.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRAWQgHgHAAgPQAAgIADgHQADgHAGgEQAHgDAGAAQAJAAAGAFQAGAEACAJIgKABQgBgFgDgDQgEgDgEAAQgHAAgFAFQgEAFAAALQAAAMAEAEQAFAGAGAAQAFAAAFgEQADgDABgIIAKABQgCAKgGAGQgGAGgKAAQgLAAgHgIg");
	this.shape_1.setTransform(71.2,11.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEAoIAAg5IAJAAIAAA5gAgEgcIAAgKIAJAAIAAAKg");
	this.shape_2.setTransform(67,10.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgPAdIAAg4IAJAAIAAAJQAEgGACgCQACgCAEAAQAFAAAFADIgEAJQgDgCgEAAQgDAAgCACQgCABgBAEQgCAFAAAGIAAAdg");
	this.shape_3.setTransform(61.3,11.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSAWQgHgIAAgOQAAgNAHgIQAIgIALAAQALAAAHAIQAIAHAAAOIAAADIgqAAQAAAJAFAFQAFAFAGAAQAGAAADgDQAEgDACgGIAKACQgDAIgFAFQgHAFgKAAQgLAAgIgIgAgKgRQgFAFAAAIIAfAAQgBgIgDgDQgEgGgHAAQgHAAgEAEg");
	this.shape_4.setTransform(56,11.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgEAdIgVg5IAKAAIAMAiIADALIAEgLIAMgiIAKAAIgVA5g");
	this.shape_5.setTransform(50.2,11.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgPAdIAAg4IAJAAIAAAJQAEgGACgCQACgCAEAAQAFAAAFADIgEAJQgDgCgEAAQgDAAgCACQgCABgBAEQgCAFAAAGIAAAdg");
	this.shape_6.setTransform(46,11.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgSAWQgIgIAAgOQAAgNAIgIQAHgIALAAQAMAAAHAIQAHAHAAAOIAAADIgqAAQABAJAFAFQAFAFAGAAQAGAAADgDQAEgDACgGIAKACQgDAIgGAFQgGAFgKAAQgMAAgHgIgAgKgRQgEAFgBAIIAfAAQgBgIgCgDQgFgGgIAAQgFAAgFAEg");
	this.shape_7.setTransform(40.7,11.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgPAZQgGgFgCgIIAKgCQABAFADADQAEAEAGAAQAGAAAEgDQADgCAAgEQAAgDgDgDQgCgBgIgCIgOgEQgEgCgCgDQgCgEAAgDQAAgEACgEQABgDADgCQADgCAEgBIAIgBQAGAAAFACQAFACACADQADAEABAFIgKABQgBgEgDgDQgDgCgFAAQgGAAgDACQgDADAAADIABACIAEADIAIADIAOAEQAEABACAEQADACAAAGQAAAFgDAEQgDAEgFACQgGADgGAAQgLAAgFgFg");
	this.shape_8.setTransform(34.8,11.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSAgQgIgHAAgOQAAgOAIgIQAHgHALAAQAMgBAHAIQAHAIAAANIAAADIgqAAQABAJAFAGQAFAEAGAAQAGAAADgCQAEgEACgGIAKACQgDAIgGAGQgGAEgKAAQgMABgHgJgAgKgGQgEAFgBAGIAfAAQgBgHgCgDQgFgGgIAAQgFAAgFAFgAgEgYIAGgQIANAAIgNAQg");
	this.shape_9.setTransform(29,10.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAWAoIgKgRIgIgLIgFgFIgEgCIgGAAIgMAAIAAAjIgLAAIAAhOIAiAAQALAAAFABQAGADADAFQADAGAAAGQABAIgGAGQgFAFgMACIAHAEQAEADAEAHIAOAWgAgXgDIAWAAQAGAAAEgCQAFgBACgEQABgDAAgEQAAgGgDgEQgFgDgJAAIgXAAg");
	this.shape_10.setTransform(22.3,10.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("Am9BmQgdAAAAgdIAAiRQAAgdAdAAIN7AAQAdAAAAAdIAACRQAAAdgdAAg");
	this.shape_11.setTransform(47.5,10.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("ADeAgQgGgHgBgOQAAgJAEgHQADgGAGgEQAGgDAHAAQAKgBAGAFQAFAFADAJIgKAAQgCgFgDgCQgEgDgEgBQgHABgFAEQgFAGAAALQABALAEAFQAEAGAHgBQAGABAEgEQAEgDABgIIAKABQgDAKgFAGQgHAFgKAAQgLABgIgJgABFAgQgHgHAAgOQAAgOAHgIQAIgHAMAAQAMgBAGAIQAIAIAAANIAAADIgrAAQABAJAEAGQAFAEAHAAQAGAAADgCQAFgEABgGIAKACQgCAIgGAGQgHAEgKAAQgMABgIgJgABNgGQgEAFgBAGIAgAAQAAgHgDgDQgFgGgHAAQgHAAgFAFgAhTAgQgIgHAAgOQAAgOAIgIQAHgHAMAAQAMgBAHAIQAHAIAAANIAAADIgrAAQABAJAFAGQAFAEAHAAQAGAAADgCQAEgEACgGIAKACQgDAIgGAGQgGAEgKAAQgNABgHgJgAhLgGQgEAFgBAGIAgAAQgBgHgCgDQgFgGgIAAQgGAAgFAFgAiLAkQgGgFgCgJIAKgCQABAGAEADQADAEAHgBQAHAAADgCQADgDAAgEQAAgDgDgCQgCgCgIgCIgPgEQgDgCgDgEQgCgDAAgDQAAgEACgDQACgDADgCQACgCAEgBIAIgBQAHAAAFACQAFABADADQACAEABAFIgJACQgBgFgDgCQgDgDgGAAQgHABgCACQgEACAAADIABADIAFACIAIACIAOAFQAFACABADQADADAAAFQAAAFgDAEQgDAFgFACQgFADgHgBQgLAAgGgEgAjIAgQgIgHAAgOQAAgOAIgIQAHgHAMAAQAMgBAHAIQAHAIAAANIAAADIgrAAQABAJAFAGQAFAEAHAAQAGAAADgCQAEgEACgGIAKACQgDAIgGAGQgGAEgKAAQgNABgHgJgAjAgGQgEAFgBAGIAgAAQgBgHgCgDQgFgGgIAAQgGAAgFAFgAESAnIAAg4IAKAAIAAA4gADCAnIAAg4IAKAAIAAA4gAB+AnIAAg4IAJAAIAAAJQADgHADgBQADgCAEAAQAFAAAFADIgEAJQgEgCgDAAQgDAAgDACQgDABAAADQgCAFAAAGIAAAegAAZAnIgVg4IAKAAIAMAhIAEAMIAEgLIANgiIAKAAIgWA4gAgaAnIAAg4IAJAAIAAAJQADgHADgBQADgCAEAAQAEAAAFADIgEAJQgDgCgDAAQgDAAgDACQgDABAAADQgCAFAAAGIAAAegAjiAnIgKgRIgIgKIgFgGIgFgCIgGAAIgMAAIAAAjIgKAAIAAhOIAjAAQALAAAFACQAGACADAFQADAGAAAHQAAAIgGAFQgFAFgMACIAHAEQAFAEADAHIAPAVgAkQgEIAXAAQAHAAAEgCQAEgBACgEQACgDAAgDQAAgGgEgEQgEgDgJgBIgZAAgAi6gYIAHgQIANAAIgNAQgAESgcIAAgLIAKAAIAAALgADCgcIAAgLIAKAAIAAALg");
	this.shape_12.setTransform(47.2,10.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("Am9BmQgdAAAAgdIAAiRQAAgdAdAAIN7AAQAdAAAAAdIAACRQAAAdgdAAgADhgQQgHADgDAHQgDAGAAAJQAAAPAHAHQAHAIAMAAQAKAAAGgGQAGgFACgKIgKgBQgBAHgDAEQgEADgGAAQgHAAgFgFQgEgFAAgMQAAgKAFgGQAEgFAIAAQAEAAAEADQADADACAGIAJgCQgCgIgGgFQgFgFgKAAQgHAAgGAEgABCgMQgHAIAAAOQAAAOAHAHQAIAIAMAAQAKAAAHgFQAGgFACgIIgKgCQgCAGgEADQgDADgGAAQgHAAgFgFQgFgFAAgJIArAAIAAgDQAAgNgIgIQgHgIgLAAQgMAAgIAIgAhWgMQgIAIAAAOQAAAOAIAHQAHAIANAAQAKAAAGgFQAGgFADgIIgKgCQgCAGgEADQgEADgFAAQgIAAgEgFQgFgFgBgJIArAAIAAgDQAAgNgHgIQgHgIgMAAQgMAAgHAIgAiWAVQACAJAGAEQAFAFAMAAQAGAAAGgCQAFgDADgEQADgEAAgFQAAgFgDgDQgCgEgEgBIgOgFIgJgDIgEgBIgBgDQAAgDADgDQADgCAHAAQAFAAADADQADACABAFIAKgCQgBgFgDgEQgCgDgFgCQgFgCgHAAIgIABQgEABgDACQgDACgBAEQgCADAAAEQAAADACADQACAEAEACIAPAEQAIACACACQADACAAADQAAAEgDACQgEADgGAAQgHAAgEgDQgDgDgBgGgAjLgMQgIAIAAAOQAAAOAIAHQAHAIANAAQAKAAAGgFQAGgFADgIIgKgCQgCAGgEADQgEADgFAAQgIAAgEgFQgFgFgBgJIArAAIAAgDQAAgNgHgIQgHgIgMAAQgMAAgHAIgAEPAmIAJAAIAAg5IgJAAgAC/AmIAJAAIAAg5IgJAAgAB7AmIAKAAIAAgeQAAgGABgFQABgDADgCQACgCAEAAQADAAAEACIADgJQgFgDgFAAQgDAAgDACQgDACgDAGIAAgJIgJAAgAAWAmIAKAAIAVg5IgKAAIgMAiIgEALIgEgLIgMgiIgKAAgAgdAmIAKAAIAAgeQAAgGABgFQABgDADgCQACgCAEAAQADAAAEACIACgJQgEgDgFAAQgDAAgDACQgDACgDAGIAAgJIgJAAgAjYAmIgOgWQgEgGgEgEIgHgEQAMgCAFgFQAGgFAAgJQAAgGgEgGQgDgFgFgCQgGgCgKAAIgkAAIAABOIALAAIAAgjIAMAAIAGAAIAFACIAFAFIAIALIAKARIANAAgAi+gaIAIAAIAMgPIgMAAgAEPgdIAJAAIAAgLIgJAAgAC/gdIAJAAIAAgLIgJAAgABFAEQABgHAEgEQAFgFAHAAQAHAAAFAGQADADAAAHgAhTAEQAAgHAFgEQAEgFAHAAQAIAAAEAGQADADABAHgAjIAEQAAgHAFgEQAEgFAHAAQAIAAAEAGQADADABAHgAkTgFIAAgbIAZAAQAJAAAEAEQAEAEAAAFQAAAEgCADQgCAEgEABQgEACgIAAg");
	this.shape_13.setTransform(47.5,10.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgFAwIAAhFIALAAIAABFgAgFgiIAAgNIALAAIAAANg");
	this.shape_14.setTransform(81.2,10);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVAbQgIgJAAgSQAAgKADgIQAEgJAIgFQAHgEAIABQAMAAAHAFQAHAGACAKIgLADQgCgHgEgFQgEgDgGAAQgIAAgGAHQgFAGAAANQAAAOAFAGQAGAHAHAAQAHAAAFgEQAFgFABgJIALACQgBAMgIAHQgIAGgMAAQgNAAgJgJg");
	this.shape_15.setTransform(76.5,11.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgFAwIAAhFIALAAIAABFgAgFgiIAAgNIALAAIAAANg");
	this.shape_16.setTransform(71.4,10);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgSAkIAAhFIALAAIAAAKQAEgHADgCQACgDAEAAQAHAAAGAEIgFALQgEgDgEAAQgEAAgCADQgDACgBAEQgCAHAAAHIAAAkg");
	this.shape_17.setTransform(64.5,11.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgWAbQgJgKAAgRQAAgQAJgKQAJgKANABQAOgBAJAKQAJAJAAARIAAADIgzAAQABAMAFAFQAGAHAIAAQAHAAAEgDQAFgEADgIIAMACQgDALgIAFQgIAHgMgBQgOAAgJgJgAgMgUQgGAFAAAJIAmAAQgBgIgEgFQgFgHgJAAQgIAAgFAGg");
	this.shape_18.setTransform(57.9,11.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgEAjIgbhFIAMAAIAQApIADAOIAEgNIAQgqIAMAAIgaBFg");
	this.shape_19.setTransform(50.8,11.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgSAkIAAhFIALAAIAAAKQADgHAEgCQACgDAFAAQAGAAAGAEIgFALQgEgDgEAAQgEAAgCADQgDACgCAEQgBAHgBAHIAAAkg");
	this.shape_20.setTransform(45.8,11.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgWAbQgJgKAAgRQAAgQAJgKQAJgKANABQAOgBAJAKQAJAJAAARIAAADIgzAAQABAMAFAFQAGAHAIAAQAHAAAEgDQAFgEADgIIAMACQgDALgIAFQgIAHgMgBQgOAAgJgJgAgMgUQgGAFAAAJIAmAAQgBgIgEgFQgFgHgJAAQgIAAgFAGg");
	this.shape_21.setTransform(39.2,11.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgTAfQgHgGgCgLIAMgCQABAIAEADQAFAEAHAAQAIAAAEgDQAEgEAAgEQAAgFgEgCIgMgDQgMgEgFgCQgFgCgCgEQgDgFAAgFQAAgEACgEQACgEAEgCQADgDAEgBQAFgBAGAAQAHAAAGACQAGACADAEQADAFABAGIgLABQgBgFgEgDQgEgDgGAAQgIAAgDADQgEACAAAEQAAABAAAAQAAABABAAQAAABAAAAQAAABABABQABACADABIAKACIARAGQAFABADAFQADADAAAHQAAAGgDAFQgEAFgGADQgHACgIAAQgNAAgHgFg");
	this.shape_22.setTransform(32,11.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgWAoQgJgKAAgRQAAgQAJgKQAJgKANAAQAOAAAJAKQAJAJAAARIAAADIgzAAQABALAFAGQAGAHAIAAQAHAAAEgEQAFgDADgIIAMACQgDAKgIAGQgIAGgMAAQgOAAgJgJgAgMgIQgGAGAAAIIAmAAQgBgIgEgEQgFgHgJAAQgIAAgFAFgAgGgeIAIgSIAQAAIgPASg");
	this.shape_23.setTransform(24.9,10);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAaAwIgMgUIgKgNIgFgHIgGgCIgHgBIgPAAIAAArIgNAAIAAhfIAqAAQANAAAHACQAHADAEAGQAEAHAAAIQAAAKgHAHQgHAGgOACIAIAFQAGAFAFAIIARAagAgdgFIAcAAQAHAAAFgCQAFgBADgEQACgEAAgFQAAgHgFgEQgFgFgKAAIgeAAg");
	this.shape_24.setTransform(16.8,10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11,p:{scaleX:1,scaleY:1}},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[]},54).to({state:[{t:this.shape_13},{t:this.shape_12}]},35).to({state:[{t:this.shape_11,p:{scaleX:1.221,scaleY:1.221}},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14}]},23).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,95,20.5);


(lib.bannière = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,1).p("AqAEXIAAhTIAAjjQBIgCBegKQALgCAKgBQABAAABAAQCrgUBlgmICMg1QCVg5AvgQIA0gSQBBgUA+gNQDJgqBoAvIAABsIAAD0Qg0gYhpABQgXAAgYABQi+AMjoBpQi2BFguAPQg7AWhTAOQimAbh4gng");
	this.shape.setTransform(84.5,30.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#26B2E3").s().p("AjDCbQgQgJgLgUQgLgVgCgaQgCgfAHgaQAGgZAMgRQAJgPAQgEQATgIAPAOQANALAGAaQgKAHgMAHQgDgOgIgFQgHgGgKADQgPAEgGATQgJATACAgQACAiAMANQALANAPgDQAGgDAHgGQAGgHAEgJIgCgXIgaAIQgCgQgBgQIAygPQACAlAFAlQgFAOgLANQgMANgMAEQgGACgGAAQgKAAgKgFgAhXhGIAYgJQArBgAXBWIgYAIIgNgoIgvAOQgEAXAAAWIgYAHQAOhhAIhugAhMAyQAQgEAQgGQgJgggNgiQgEAngGAlgAgEhhIAygQQATgHAKADQAKACAHAMQAIAMADASQAEAXgHASQgHARgPAKQAIAFAGAGQAFAHAJAUIAPAiIgcAIQgKgSgJgSQgKgUgDgFQgEgFgEgBQgDgBgJADIgFABIADBQIgXAIQABhegVhmgAA/hTQgDAAgOAFIgTAGQAFAbACAaIASgGQASgFAEgEQADgFACgGQACgHgBgJQgDgMgEgFQgDgFgGAAIgBAAgACQAlQgPgVgDgwQgCgfABgYQABgQAFgOQAFgPAIgIQAKgMAPgFQAbgIARAXQAQAXAGAzQAEAygPAfQgPAegZAIQgGACgGAAQgRAAgLgQgACth6QgPAFgGAUQgGAUAEAkQACAiAKAOQAJAPAOgFQAOgEAIgSQAJgVgDgkQgEglgLgNQgHgLgKAAQgEAAgEABg");
	this.shape_1.setTransform(60.4,37.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjJCVQgMgNgCgiIAUgKQADAUAHAHQAGAHAKgCQALgDAFgJQAFgLgBgLIgDgMQgEgFgFgCIgSgEQgSgEgIgKQgNgNgBgZQgBgPAEgPQAEgQAKgJQAJgLAMgEQAVgHALAPQAJAOABAeIgVAHQgCgQgFgEQgFgHgIADQgKADgFAKQgEAFABAIQAAAHADAEQAFAGAQACQAQACAJAHQAHAFAGANQAGAMADAUQABASgEAQQgEAPgJALQgKAKgOADIgMACQgNAAgJgKgAh1hHIAVgFQAUBCAdBAQgIhFADhJIATgGQgGBvAXBjIgWAFQgjg7gXg/QAEBEAKBBIgVAFQgRhjADhtgAAKBVQgTgYgEgzQgBggAEgXQAEgTAGgOQAFgPAIgHQAJgMAMgCQAWgHAQAbQAOAaACA1QABAzgGAfQgIAegWAGIgJABQgSAAgQgTgAAjhNQgNADgIAVQgIAUACAkQACAlALAQQALAQANgDQAMgEAFgTQAFgUgBgkQgBgmgIgQQgHgOgKAAIgFABgABZh8IAVgFQANBGALBHQAIhNABhIQALgEAMgDQAVBEALBJQAHhPgGhGQAJgEALgCQAEBmgHBvIgWAHQgVhJgMhOQgKBUACBOIgWAGQgchigOhpg");
	this.shape_2.setTransform(107,23.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#32150F").s().p("ApxEXIAAhTIAAjjQBIgCBegKIAUgDIADAAQCrgUBlgmICMg1QCUg5AwgQIA0gSQBBgUA+gNQDIgqBoAvIAABsIAEACIAUAJIAVAJIAGADIAYAMQAnAWAiAYIAcAWIh6BdQAGAFAOAZIABABQAJAQAMAaIAaA1IAaA3IAcA8IgcgUQgagSgagPIgVgMIgYgLIgbgNQg1gWg5gNQhIgQgvACIABhNIAwgBIACAAIAAAAIACAAIAAAAIAAAAQBlAAAzAXIAAj0IAAD0QgzgXhlAAIAAAAIAAAAIgCAAIAAAAIgCAAIgwABQi+AMjnBpQi3BFguAPQg7AWhTAOQhEALg8AAQhWAAhGgXgAmeAfQgPAFgKAOQgMARgFAbQgIAZADAfQABAbALAVQALAUAQAJQAQAHARgEQALgEAMgNQALgNAGgOQgGgmgBglIgyAPQAAAQADAQIAZgIIADAYQgFAIgGAHQgHAGgGADQgOAEgLgOQgNgNgCgiQgCggAJgSQAHgVAPgEQAJgDAIAHQAHAGADANQAMgGALgIQgGgagOgMQgJgIgLAAQgHAAgHACgAk5ABQgJBugNBiIAYgHQAAgXADgXIAvgOIAOAoIAZgIQgZhVgqhgIgYAIgAi0gqIgyAQQAWBngCBdIAXgHIgDhQIAFgBQAJgEAEACQAEAAADAGQAEAEAKAUQAIATAKASIAcgJIgOghQgKgUgFgHQgGgIgHgFQAPgJAHgRQAHgSgEgWQgDgTgJgLQgHgNgKgCIgGgBQgJAAgOAFgAg5hVQgOAFgKALQgIAJgFAOQgGAOgBARQAAAWACAgQACAwAPAWQAPAVAagHQAZgIAPgfQAOgggEgxQgGgzgQgWQgMgSgSAAQgHAAgHADgAAXAjQACAhAMAOQANANAVgFQAOgEAKgJQAJgLAEgQQAEgQgBgSQgDgTgGgMQgGgNgHgFQgJgGgQgCQgQgDgFgFQgDgEAAgIQgBgIAEgGQAFgJAKgDQAIgDAFAGQAFAFACAQIAVgHQgBgegJgPQgLgPgVAIQgMADgJALQgKAKgEAPQgEAQABAQQABAYANAOQAIAKASADIASAEQAFACAEAEIADAMQABALgFALQgFAJgLAEQgKABgGgGQgHgIgDgUIgUALgAB5iKQgDBuARBhIAVgEQgKhBgEhFQAXBAAjA7IAWgFQgXhjAGhvIgTAFQgDBJAIBHQgdhBgUhDIgVAGgAERi2QgMADgJALQgIAIgGAPQgGAOgEASQgEAYABAhQAEAyAUAYQAUAWAXgFQAWgGAIgdQAGgfgBg0QgCg1gOgZQgNgWgRAAIgIABgAFIjAQAOBqAcBiIAWgGQgChOAKhUQAMBNAVBKIAWgGQAHhwgEhnQgLACgJAEQAGBGgHBQQgLhKgVhDQgMACgLAEQgBBJgIBOQgLhIgNhHIgVAFgAAcDyQgHgFgEgMQgCgNABgHQABgIAKgCQAFgCAFABQAEACADAFIgIAFQgBgBAAgBQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQgDABAAAEQgCADADAIQAAgGAHAAQAFgDAGADQAFADACAHQACAHgCAGQgDAFgGAEIgEAAQgGAAgEgCgAAiDaQgDABgBADQgCADACAEQABAEADACIAGAAQAAAAABAAQAAAAABgBQAAAAAAgBQABAAAAgBQABgCgBgFQgCgFgCgBIgDgBIgCAAgAAtC3IAXgJIACAFQgJADgIAEIACAHIAQgGIABAFIgPAGIADAJIARgHIACAFIgYAJIgKgfgABJCtQAEgDAFgBIANASIgCgXIAKgEIAKAfIgGACIgIgYIACAbIgGACIgOgWIAIAZIgGACIgKgegAqMC6IgWgJIgVgKIgGgCIgYgNQgpgXgjgaQgPgLgOgMIB+hiQgGgEgPgbIAAgBIgWgsIgbg5Igbg5Igdg/IAdAVQAaATAcAQIAWAMIAYAMIAbANQA4AYA6ANQBKARAxgCIgCBQIgUADQheAKhIACIAADjIgbgKgACfCMQAQgIASgHQgBAEADAEIgZALIADALIAYgKIADAIIgXAKIAEAOIAagKIADAIIgjAOIgQgxgABsCdIAXgKIACAFIgQAHIACAHIAPgHIACAGIgPAHIADAIQAIgEAJgDIACAFQgNAEgLAGIgLgfgADKB6QAIgEAJgCQAGgDADAAQAEAAAFACQAEACAEAFQABAEAEAIQACAGAAAFQAAAGgCAFIgGAGIgIAEIgRAGIgRgygADiB7IgIACIgEACIALAiIAHgDQADgCADgBIADgDIABgGIgCgJQgCgHgCgCQgDgEgCAAIgDgBIgCAAgAD6BqQAEgDAGgBQAGAaAKAZIgKADQgKgagGgYgAEdBpQgJABgHADIgCgIQATgGAYgFQAAAEACAFQgKABgHADIAMAqIgKACQgHgVgFgVgAE8BZIALgDIAMAzQgGABgEACIgNgzgAFgCAQgIgGgDgMQgDgIADgGQAAgEAEgDQABgEAEgCQAEgEAIgBQALgDAIAHQAJAFABANQABANgFAIQgFAHgKADIgHABQgIAAgFgEgAFrBXQgHAAgCAHQgEAFADAJQAAAIAGAEQAEACAHAAQAGgCADgEIACgOQgCgJgEgEQgGgCgEAAIgCAAgAGLBKIAJgCQANAOAJAQQgBgRgEgQQADgCAFABIAHAyQgFgBgDACIgVgeIAEAhQgFAAgEACQgCgagFgYgAkkAtQAMAjAKAgQgRAGgPAEQAGglAEgogAhABPQgJgPgCgiQgEgjAFgUQAGgVAQgEQAOgGAKAQQALANAEAkQADAkgJAUQgIATgOAFIgGABQgKAAgHgLgAjHAAIATgHQAOgFADAAQAHAAAEAGQAEAFACAKQABAJgBAHQgCAHgEAEQgEAEgRAFIgSAGQgDgagFgZgAEEgLQgLgQgCgkQgCglAIgVQAIgUANgEQANgDAJAQQAIAQABAmQABAlgFAUQgFAUgMACIgEABQgKAAgKgNgAmjhtQAOgGASgCIACAIIgXAGQAAAGADAFQAKgEAKgBIACAIQgNAAgIAGIACAUQgHAAgDAEIgHgygAl6h4IAlgIQgBAEADAFQgQABgLAFQAAAEADAGQAMgEAOgBQgBAEADAEQgOABgMAEIADAOQANgEAQgBIACAIQgUADgUAFQgDgbgIgXgAk7hUQgIgEgBgHIAJgEIAGAHIAHAAIAHgDQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQgBgBAAgBQAAgBAAAAQgBgBAAAAQAAAAAAABIgEgBQgEgCgFABQgIgDgFABQgFgEgDgFQgCgFADgDQAAgFAFgBQABgDAIgBQAIgEAGAFQAFABAEAJIgKADQgCgHgCABQgFgBgCABQgFABgCACQAAAAgBAAQAAABAAAAQAAABAAAAQAAABABABQAAAAAAAAQAAABAAAAQABABAAAAQABAAABABQACgBAIACQAGgBAFADQAEAAADADQADACADAGIgBAIQgCAFgCACQgGABgFAEIgFAAQgHAAgEgCgAkSiFQgIAAgGADQgDgFABgEIAmgKQgBAFADAEQgIABgHACQAIAWAGAVQgEgBgFAEIgOgqgAj2iXIAJgDIARA0QgGABgEACIgQg0gAjpibIAKgDQALARANARQgCgWABgUQAEgCAGgBQgCAcABAdIgJADIghgugAiwitQADgDAGgBQAQAWATAXIgKAEQgFgFgDgFIgSAFIAAANIgLAEIADg5gAioiOQAGgDAHgBQgHgLgGgFQgBAKABAKgAiSi2QAGgDAFABQADASAKAWIAXgIQAAAEAFAFQgUADgPAHIgRgxg");
	this.shape_3.setTransform(83.1,30.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,166.2,62.4);


(lib.accroche = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC9900").s().p("AgHArIAAgQIAPAAIAAAQgAgHAWIAAgFQAAgHADgEQACgFAGgFIAJgHQACgDAAgEQAAgFgEgEQgEgCgGAAQgGAAgEADQgEAEgBAGIgQgBQABgLAIgHQAIgIANAAQAOAAAIAIQAJAHAAAKQAAAGgDAEQgDAGgLAHIgGAHIgBAKg");
	this.shape.setTransform(215.1,8.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC9900").s().p("AgWAWQgGgJAAgNQAAgOAIgJQAIgJAMABQANAAAIAJQAIAIAAATIgpAAQABAHADAEQAEAEAFAAQAEAAACgCQADgCABgFIARADQgDAJgHAEQgHAGgKAAQgPAAgIgLgAgIgPQgDAEAAAHIAXAAQAAgHgDgFQgEgDgFAAQgEAAgEAEg");
	this.shape_1.setTransform(204.7,10.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CC9900").s().p("AgSAbQgIgFgCgJIARgDQABAFACADQAEACAFAAQAGAAADgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgFgCQgTgEgFgEQgIgEAAgIQAAgJAHgFQAGgGANABQAMAAAHADQAFAEADAJIgQADQgBgEgCgCQgDgCgFAAQgGAAgCACQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAIABAEIAPAEQANADAFAEQAFADAAAIQAAAJgHAGQgIAHgNAAQgMAAgHgGg");
	this.shape_2.setTransform(198,10.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC9900").s().p("AgSAbQgIgFgCgJIARgDQABAFACADQAEACAEAAQAHAAADgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgFgCQgTgEgFgEQgIgEAAgIQAAgJAHgFQAGgGANABQAMAAAGADQAGAEADAJIgQADQgBgEgCgCQgEgCgEAAQgGAAgDACQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAIABAEIAPAEQANADAFAEQAFADAAAIQAAAJgHAGQgIAHgOAAQgLAAgHgGg");
	this.shape_3.setTransform(191.3,10.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CC9900").s().p("AgHArIAAg9IAPAAIAAA9gAgHgaIAAgQIAPAAIAAAQg");
	this.shape_4.setTransform(186.4,8.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC9900").s().p("AgHArIAAhVIAPAAIAABVg");
	this.shape_5.setTransform(183.1,8.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CC9900").s().p("AgVAnQgGgGAAgIIAAgCIATACQAAABAAABQAAABABAAQAAABAAAAQAAABABAAQACABAEAAQAHAAADgBQACgBABgEIABgHIAAgJQgHAKgLAAQgMAAgIgLQgFgIAAgMQAAgPAHgJQAIgHALAAQAKAAAIAKIAAgJIAPAAIAAA3QAAALgBAFQgCAFgEAEQgDADgFABQgGACgIAAQgPABgHgGgAgJgbQgDAFAAAJQAAALADADQAEAEAFAAQAGAAAEgEQAEgEAAgJQAAgJgEgGQgEgEgGAAQgFAAgEAEg");
	this.shape_6.setTransform(177.6,11.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC9900").s().p("AgWAWQgGgJAAgNQAAgOAIgJQAIgJAMABQANAAAIAJQAIAIAAATIgpAAQABAHADAEQAEAEAFAAQAEAAACgCQADgCABgFIARADQgDAJgHAEQgHAGgKAAQgPAAgIgLgAgIgPQgDAEAAAHIAXAAQAAgHgDgFQgEgDgFAAQgEAAgEAEg");
	this.shape_7.setTransform(167.4,10.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CC9900").s().p("AgWAjQgHgJAAgPQAAgPAHgIQAIgIALAAQAJAAAIAIIAAgfIAQAAIAABVIgPAAIAAgJQgEAFgFADQgFADgEAAQgLAAgIgJgAgJgDQgEAEAAAJQAAAKADAEQAEAHAGAAQAGAAAEgFQAEgFAAgKQAAgKgEgEQgEgFgGAAQgFAAgEAFg");
	this.shape_8.setTransform(160.2,8.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CC9900").s().p("AgCApQgDgBgCgDIgCgGIgBgMIAAgaIgHAAIAAgNIAHAAIAAgMIAQgKIAAAWIALAAIAAANIgLAAIAAAYIAAAJIABACIADABIAHgCIABANQgFADgIAAQgEAAgDgCg");
	this.shape_9.setTransform(151.4,9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#CC9900").s().p("AgWAWQgGgJAAgNQAAgOAIgJQAIgJAMABQANAAAIAJQAIAIAAATIgpAAQABAHADAEQAEAEAFAAQAEAAACgCQADgCABgFIARADQgDAJgHAEQgHAGgKAAQgPAAgIgLgAgIgPQgDAEAAAHIAXAAQAAgHgDgFQgEgDgFAAQgEAAgEAEg");
	this.shape_10.setTransform(146,10.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#CC9900").s().p("AgWAWQgGgJAAgNQAAgOAIgJQAIgJAMABQANAAAIAJQAIAIAAATIgpAAQABAHADAEQAEAEAFAAQAEAAACgCQADgCABgFIARADQgDAJgHAEQgHAGgKAAQgPAAgIgLgAgIgPQgDAEAAAHIAXAAQAAgHgDgFQgEgDgFAAQgEAAgEAEg");
	this.shape_11.setTransform(136,10.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CC9900").s().p("AgSAdQgFgDgCgFQgCgFAAgJIAAgmIAQAAIAAAdQAAAMABADQABADACABQADACADAAQAEAAADgCQADgDABgDQACgDAAgNIAAgaIAQAAIAAA9IgPAAIAAgJQgEAFgFADQgFADgGAAQgGAAgFgDg");
	this.shape_12.setTransform(129,10.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#CC9900").s().p("AAOArIAAgeQgDAEgFACQgFACgEABQgLgBgHgHQgIgKAAgPQAAgPAIgIQAHgJAMABQAEAAAFACQAFADADAFIAAgJIAPAAIAABUgAgJgZQgDAFAAAKQAAAKADAEQAEAFAFgBQAGAAAEgEQAFgFAAgKQAAgKgFgEQgDgEgHgBQgEABgFAEg");
	this.shape_13.setTransform(121.6,11.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#CC9900").s().p("AgHArIAAg9IAPAAIAAA9gAgHgaIAAgQIAPAAIAAAQg");
	this.shape_14.setTransform(116.3,8.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#CC9900").s().p("AgSAbQgIgFgCgJIARgDQABAFACADQAEACAEAAQAHAAADgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgFgCQgTgEgFgEQgIgEAAgIQAAgJAHgFQAGgGANABQAMAAAGADQAGAEADAJIgQADQgBgEgCgCQgEgCgEAAQgGAAgCACQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAIABAEIAPAEQANADAFAEQAFADAAAIQAAAJgHAGQgIAHgOAAQgLAAgHgGg");
	this.shape_15.setTransform(111.2,10.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#CC9900").s().p("AgSAdQgFgDgCgFQgCgFAAgJIAAgmIAQAAIAAAdQAAAMABADQABADACABQADACADAAQAEAAADgCQADgDABgDQACgDAAgNIAAgaIAQAAIAAA9IgPAAIAAgJQgEAFgFADQgFADgGAAQgGAAgFgDg");
	this.shape_16.setTransform(104.3,10.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#CC9900").s().p("AAdAgIAAgjQAAgJgCgDQgCgDgFAAQgDAAgDACQgDACgBAEQgCAEAAAIIAAAeIgPAAIAAghIgBgMIgDgEQgCgBgDAAQgEAAgDACQgDACgBAEIgBAMIAAAeIgRAAIAAg9IAPAAIAAAIQAIgKAMAAQAGAAAEADQADACADAFQAEgFAFgCQAFgDAFAAQAHAAAFADQAFADACAFQACAEAAAJIAAAng");
	this.shape_17.setTransform(95.3,10);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#CC9900").s().p("AgWAWQgGgJAAgNQAAgOAIgJQAIgJAMABQANAAAIAJQAIAIAAATIgpAAQABAHADAEQAEAEAFAAQAEAAACgCQADgCABgFIARADQgDAJgHAEQgHAGgKAAQgPAAgIgLgAgIgPQgDAEAAAHIAXAAQAAgHgDgFQgEgDgFAAQgEAAgEAEg");
	this.shape_18.setTransform(83.3,10.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#CC9900").s().p("AgWAjQgHgJAAgPQAAgPAHgIQAIgIALAAQAJAAAIAIIAAgfIAQAAIAABVIgPAAIAAgJQgEAFgFADQgFADgEAAQgLAAgIgJgAgJgDQgEAEAAAJQAAAKADAEQAEAHAGAAQAGAAAEgFQAEgFAAgKQAAgKgEgEQgEgFgGAAQgFAAgEAFg");
	this.shape_19.setTransform(76.2,8.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#CC9900").s().p("AgOA4IAHgPIAEgOIACgNIABgOQAAgMgDgNQgDgNgIgRIALAAQAIAMAFAPQAFANAAAPQAAALgEAOQgEAQgJAPg");
	this.shape_20.setTransform(67.2,10.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#CC9900").s().p("AgWAWQgGgJAAgNQAAgOAIgJQAIgJAMABQANAAAIAJQAIAIAAATIgpAAQABAHADAEQAEAEAFAAQAEAAACgCQADgCABgFIARADQgDAJgHAEQgHAGgKAAQgPAAgIgLgAgIgPQgDAEAAAHIAXAAQAAgHgDgFQgEgDgFAAQgEAAgEAEg");
	this.shape_21.setTransform(62,10.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#CC9900").s().p("AADA4QgIgOgEgOQgFgOAAgOQAAgQAGgPQAFgNAHgLIALAAQgIARgDANQgDANAAAMQAAAKACAKQABAKADAJIAIARg");
	this.shape_22.setTransform(56.8,10.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#CC9900").s().p("AgWAiQgGgJAAgNQAAgOAIgJQAIgJAMABQANAAAIAJQAIAIAAATIgpAAQABAHADAEQAEAEAFAAQAEAAACgCQADgCABgFIARADQgDAJgHAEQgHAGgKAAQgPAAgIgLgAgIgDQgDADAAAHIAXAAQAAgHgDgEQgEgDgFAAQgEAAgEAEgAgIgaIAIgRIASAAIgQARg");
	this.shape_23.setTransform(51.3,8.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#CC9900").s().p("AAMAgIAAggQAAgJgBgDQgBgDgCgCQgDgBgDAAQgDAAgEACQgDACgBAEQgCAEAAAKIAAAcIgQAAIAAg9IAPAAIAAAJQAIgLAMAAQAFAAAFACQAEACACADQADADABAEIAAALIAAAmg");
	this.shape_24.setTransform(44.3,10);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#CC9900").s().p("AgPAcQgIgEgEgHQgEgIAAgJQAAgIAEgIQAEgIAIgEQAGgDAJAAQAOAAAJAJQAJAIAAAOQAAAOgJAJQgJAKgOAAQgIAAgHgFgAgKgNQgEAEAAAJQAAAJAEAFQAFAFAFAAQAHAAAEgFQAEgFAAgJQAAgJgEgEQgEgFgHAAQgFAAgFAFg");
	this.shape_25.setTransform(37,10.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#CC9900").s().p("AgHArIAAg9IAPAAIAAA9gAgHgaIAAgQIAPAAIAAAQg");
	this.shape_26.setTransform(31.6,8.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#CC9900").s().p("AgSAbQgIgFgCgJIARgDQABAFACADQAEACAEAAQAHAAADgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgFgCQgTgEgFgEQgIgEAAgIQAAgJAHgFQAGgGANABQAMAAAHADQAFAEADAJIgQADQgBgEgCgCQgDgCgFAAQgGAAgCACQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAIABAEIAPAEQANADAFAEQAFADAAAIQAAAJgHAGQgIAHgOAAQgLAAgHgGg");
	this.shape_27.setTransform(26.5,10.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#CC9900").s().p("AgSAbQgIgFgCgJIARgDQABAFACADQAEACAEAAQAHAAADgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgFgCQgTgEgFgEQgIgEAAgIQAAgJAHgFQAGgGANABQAMAAAGADQAGAEADAJIgQADQgBgEgCgCQgEgCgEAAQgGAAgDACQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAIABAEIAPAEQANADAFAEQAFADAAAIQAAAJgHAGQgIAHgOAAQgLAAgHgGg");
	this.shape_28.setTransform(19.9,10.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#CC9900").s().p("AgXAbQgFgFAAgIQAAgFADgEQACgFAFgBQAEgCAIgBQALgDAFgCIAAgBQgBgFgCgCQgCgCgFAAQgFAAgCABQgDACgCAFIgOgDQACgJAGgFQAHgDALAAQALAAAFACQAFADACAEQADADAAALIAAASIABANIACAIIgQAAIgCgFIgBgCQgEAEgEADQgEACgFAAQgKgBgGgFgAAAAEQgHABgBACQgEACAAAEQAAADADACQACADAEAAQAEAAAEgDQADgDABgCIABgIIAAgEIgKADg");
	this.shape_29.setTransform(13.4,10.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#CC9900").s().p("AggArIAAhVIAcAAQAPAAAFABQAHACAFAHQAFAGAAAKQAAAJgDAFQgDAEgEADQgEAEgFABIgRAAIgMAAIAAAhgAgPgDIAKAAQAJAAAEgCQADgBACgCQACgDAAgEQAAgFgDgDQgCgDgFgBIgLAAIgJAAg");
	this.shape_30.setTransform(6.2,8.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,220.8,17.7);


(lib.bouton_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_12 = function() {
		this.gotoAndPlay(Math.round(Math.random()*3));
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(12).call(this.frame_12).wait(78));

	// Calque_1
	this.instance = new lib.bouton("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(47.5,10.2,1,1,0,0,0,47.5,10.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.2,scaleY:1.2,x:47.6,y:10.3,startPosition:89},12).wait(78));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,95,20.5);


// stage content:
(lib.projet_garosnow_728x90_animation = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// skieur
	this.instance = new lib.skieur("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-54.8,-34.2,1,1,0,0,0,54.3,33.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(109).to({_off:false},0).to({x:272.1,y:43.8},35).wait(216));

	// leitmotive
	this.instance_1 = new lib.leitmotive("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-105.9,74.3,1,1,0,0,0,104.9,10.4);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(59).to({_off:false},0).to({x:112.1,y:75.9},40).wait(261));

	// 6eme edition
	this.instance_2 = new lib.bannière("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(109.3,45.7,0.049,0.049,0,0,0,83.3,29.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(42).to({_off:false},0).to({regX:83,regY:30.2,scaleX:0.6,scaleY:0.6},28,cjs.Ease.backOut).wait(290));

	// ski
	this.instance_3 = new lib.skis("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(494,117.6,1,1,0,0,0,10.3,27.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(76).to({_off:false},0).to({y:63.1},8).wait(276));

	// accroche
	this.instance_4 = new lib.accroche("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(117.6,-8.7,1,1,0,0,0,110.4,8.8);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(24).to({_off:false},0).to({y:15.3},10).wait(326));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_154 = new cjs.Graphics().p("Af7B0IgHABIAFgFIgDgHIAHAEIAFgFIgBAHIAGAEIgHABIgBAHg");
	var mask_graphics_155 = new cjs.Graphics().p("AfdBtIgmADIAcgaIgPgjIAhASIAdgZIgHAlIAhAUIgmAFIgIAlg");
	var mask_graphics_156 = new cjs.Graphics().p("Ae/BlIhEAHIAxgwIgbg+IA9AfIAzgsIgLBCIA7AjIhEAKIgQBDg");
	var mask_graphics_157 = new cjs.Graphics().p("AehBeIhjAJIBHhFIgnhbIBYAvIBLhCIgRBhIBVAzIhiAOIgWBhg");
	var mask_graphics_158 = new cjs.Graphics().p("AeDBWIiCAMIBehbIg0h2IBzA9IBihWIgWCAIBwBCIiBASIgdB/g");
	var mask_graphics_159 = new cjs.Graphics().p("AdlBPIihAOIB0hvIg/iTICOBLIB5hqIgcCeICKBSIifAWIgkCdg");
	var mask_graphics_160 = new cjs.Graphics().p("AdGBOIi+ARICJiEIhLiwICpBaICQh+IghC8IClBiIi+AaIgqC7g");
	var mask_graphics_161 = new cjs.Graphics().p("AcoBbIjdAUICgiaIhYjMIDFBoICniSIgmDbIC+BwIjcAgIgxDYg");
	var mask_graphics_162 = new cjs.Graphics().p("AcKBnIj8AXIC2ivIhkjoIDgB2IC+imIgrD5IDZCAIj7AkIg4D2g");
	var mask_graphics_163 = new cjs.Graphics().p("AbsB0IkbAZIDMjEIhvkFID6CFIDWi7IgxEYID0CQIkZAoIg/EVg");
	var mask_graphics_164 = new cjs.Graphics().p("AbOCAIk5AdIDhjaIh7khIEWCTIDsjPIg2E2IEOCgIk3AsIhGEzg");
	var mask_graphics_165 = new cjs.Graphics().p("AawCNIlYAfID4jvIiIk9IExChIEEjjIg8FUIEpCwIlWAwIhNFRg");
	var mask_graphics_166 = new cjs.Graphics().p("AaRCZIl2AiIEOkEIiUlZIFMCvIEbj3IhAFyIFCDAIl0A1IhTFug");
	var mask_graphics_167 = new cjs.Graphics().p("AZzCmImVAlIEkkaIifl2IFnC+IEykLIhGGQIFdDPImTA6IhaGMg");
	var mask_graphics_168 = new cjs.Graphics().p("AZVCyImzAoIE6kvIismSIGCDNIFJkgIhLGvIF3DeImxA+IhgGqg");
	var mask_graphics_169 = new cjs.Graphics().p("AY3C/InSAqIFQlEIi4muIGdDbIFhk0IhRHNIGSDuInPBCIhoHIg");
	var mask_graphics_170 = new cjs.Graphics().p("AYZDMInxAtIFmlaIjEnKIG5DpIF3lIIhWHrIGtD+InuBGIhvHmg");
	var mask_graphics_171 = new cjs.Graphics().p("AX7DYIoQAwIF9lvIjRnnIHUD4IGPldIhbIKIHGEOIoMBKIh1IFg");
	var mask_graphics_172 = new cjs.Graphics().p("AXcDlIotAyIGSmEIjcoDIHvEGIGllxIhgIoIHhEeIorBPIh8Iig");
	var mask_graphics_173 = new cjs.Graphics().p("AW+DxIpMA2IGomaIjoofIIKEUIG9mFIhmJGIH7EuIpJBTIiDJAg");
	var mask_graphics_174 = new cjs.Graphics().p("AWgD+IprA4IG/mvIj1o8IIlEjIHUmZIhrJkIIWE9IpoBYIiJJeg");
	var mask_graphics_175 = new cjs.Graphics().p("AWCEKIqKA7IHVnFIkBpXIJBExIHrmtIhxKCIIwFNIqFBcIiRJ8g");
	var mask_graphics_176 = new cjs.Graphics().p("AVkEXIqoA9IHqnaIkMpzIJbE/IICnBIh1KhIJKFcIqkBgIiYKag");
	var mask_graphics_177 = new cjs.Graphics().p("AVGEjIrHBBIIAnwIkYqPIJ2FNIIanVIh7K/IJlFsIrDBkIieK4g");
	var mask_graphics_178 = new cjs.Graphics().p("AUnEwIrlBDIIXoFIklqsIKSFdIIwnqIiALdIJ/F8IrhBpIilLVg");
	var mask_graphics_179 = new cjs.Graphics().p("AUJE8IsEBGIItoaIkxrIIKtFrIJHn/IiFL8IKaGMIsABtIisL0g");
	var mask_graphics_180 = new cjs.Graphics().p("ATrFJIsiBJIJCowIk8rkILIF5IJeoTIiLMaIK0GcIseBxIiyMSg");
	var mask_graphics_181 = new cjs.Graphics().p("ATNFWItBBLIJZpFIlJsAILjGHIJ1onIiPM4ILOGrIs8B2Ii6Mwg");
	var mask_graphics_182 = new cjs.Graphics().p("ASvFiItgBOIJvpaIlVsdIL+GWIKNo7IiVNWILoG7ItaB6IjBNOg");
	var mask_graphics_183 = new cjs.Graphics().p("ASRFvIt/BRIKFpwIlhs5IMaGkIKjpPIiaN1IMDHKIt5B/IjHNrg");
	var mask_graphics_184 = new cjs.Graphics().p("ARyF7IucBUIKbqFIlutVIM1GyIK7pjIigOTIMeHaIuYCDIjOOJg");
	var mask_graphics_185 = new cjs.Graphics().p("ARUGIIu7BWIKxqaIl5tyINPHBILSp3IilOxIM4HqIu2CHIjUOng");
	var mask_graphics_186 = new cjs.Graphics().p("AQ2GUIvaBaILHqwImFuOINrHPILpqLIiqPPINSH6IvVCLIjbPFg");
	var mask_graphics_187 = new cjs.Graphics().p("AQYGhIv5BcILerFImSuqIOGHdIMAqgIivPuINsIKIvyCPIjjPkg");
	var mask_graphics_188 = new cjs.Graphics().p("AP6GtIwWBfILyraImevGIOiHrIMXq0Ii1QMIOHIZIwRCUIjpQCg");
	var mask_graphics_189 = new cjs.Graphics().p("APcG6Iw1BhIMIrvImpvjIO8H7IMurJIi6QqIOhIpIwvCZIjwQfg");
	var mask_graphics_190 = new cjs.Graphics().p("AO9HGIxTBlIMfsFIm2v/IPXIJINGrdIjARIIO8I5IxOCdIj3Q9g");
	var mask_graphics_191 = new cjs.Graphics().p("AOfHTIxyBnIM1saInCwbIPzIXINcrxIjERnIPWJIIxtChIj9Rbg");
	var mask_graphics_192 = new cjs.Graphics().p("AOBHfIyQBqINKsvInOw3IQOIlIN0sFIjKSFIPwJYIyLClIkER5g");
	var mask_graphics_193 = new cjs.Graphics().p("ANjHsIyvBtINgtFInZxUIQoI0IOLsZIjPSjIQLJoIypCpIkMSXg");
	var mask_graphics_194 = new cjs.Graphics().p("AM7H5IzNBvIN2taInlxwIRDJCIOisuIjUTCIQlJ4IzICtIkSS1g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(154).to({graphics:mask_graphics_154,x:205.5,y:12.3}).wait(1).to({graphics:mask_graphics_155,x:207.6,y:14.3}).wait(1).to({graphics:mask_graphics_156,x:209.7,y:16.3}).wait(1).to({graphics:mask_graphics_157,x:211.7,y:18.3}).wait(1).to({graphics:mask_graphics_158,x:213.8,y:20.3}).wait(1).to({graphics:mask_graphics_159,x:215.8,y:22.3}).wait(1).to({graphics:mask_graphics_160,x:217.9,y:23.6}).wait(1).to({graphics:mask_graphics_161,x:219.9,y:23.6}).wait(1).to({graphics:mask_graphics_162,x:222,y:23.6}).wait(1).to({graphics:mask_graphics_163,x:224.1,y:23.6}).wait(1).to({graphics:mask_graphics_164,x:226.1,y:23.6}).wait(1).to({graphics:mask_graphics_165,x:228.2,y:23.6}).wait(1).to({graphics:mask_graphics_166,x:230.2,y:23.6}).wait(1).to({graphics:mask_graphics_167,x:232.3,y:23.6}).wait(1).to({graphics:mask_graphics_168,x:234.3,y:23.5}).wait(1).to({graphics:mask_graphics_169,x:236.4,y:23.5}).wait(1).to({graphics:mask_graphics_170,x:238.5,y:23.5}).wait(1).to({graphics:mask_graphics_171,x:240.5,y:23.5}).wait(1).to({graphics:mask_graphics_172,x:242.6,y:23.5}).wait(1).to({graphics:mask_graphics_173,x:244.6,y:23.5}).wait(1).to({graphics:mask_graphics_174,x:246.7,y:23.5}).wait(1).to({graphics:mask_graphics_175,x:248.7,y:23.5}).wait(1).to({graphics:mask_graphics_176,x:250.8,y:23.5}).wait(1).to({graphics:mask_graphics_177,x:252.9,y:23.5}).wait(1).to({graphics:mask_graphics_178,x:254.9,y:23.5}).wait(1).to({graphics:mask_graphics_179,x:257,y:23.5}).wait(1).to({graphics:mask_graphics_180,x:259,y:23.5}).wait(1).to({graphics:mask_graphics_181,x:261.1,y:23.4}).wait(1).to({graphics:mask_graphics_182,x:263.1,y:23.4}).wait(1).to({graphics:mask_graphics_183,x:265.2,y:23.4}).wait(1).to({graphics:mask_graphics_184,x:267.3,y:23.4}).wait(1).to({graphics:mask_graphics_185,x:269.3,y:23.4}).wait(1).to({graphics:mask_graphics_186,x:271.4,y:23.4}).wait(1).to({graphics:mask_graphics_187,x:273.4,y:23.4}).wait(1).to({graphics:mask_graphics_188,x:275.5,y:23.4}).wait(1).to({graphics:mask_graphics_189,x:277.5,y:23.4}).wait(1).to({graphics:mask_graphics_190,x:279.6,y:23.4}).wait(1).to({graphics:mask_graphics_191,x:281.7,y:23.4}).wait(1).to({graphics:mask_graphics_192,x:283.7,y:23.4}).wait(1).to({graphics:mask_graphics_193,x:285.8,y:23.4}).wait(1).to({graphics:mask_graphics_194,x:286.9,y:23.6}).wait(166));

	// dates
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#266CA1").s().p("AgdA7QgPgLAAgUQAAgLAGgJQAFgIAMgGQgKgDgEgIQgFgHAAgKQAAgOALgLQAKgKATAAQATAAALAKQALALAAAOQAAAKgFAIQgFAGgJAEQALAFAGAIQAGAIAAAMQAAATgMALQgMANgUAAQgSAAgMgLgAgNALQgFAHAAAIQAAAKAGAHQAFAFAHAAQAJAAAFgFQAFgGAAgLQAAgJgFgGQgGgGgIgBQgIABgFAGgAgLgrQgEAEAAAHQAAAIAEAFQAEAEAHAAQAHAAAFgEQAEgFAAgIQAAgHgEgEQgFgFgHAAQgHAAgEAFg");
	this.shape.setTransform(506.2,16.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#266CA1").s().p("AADBEIAAhhQgMANgUAHIAAgYQAKgDAMgKQALgJAFgMIAVAAIAACHg");
	this.shape_1.setTransform(495,15.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#266CA1").s().p("AgfA2QgMgPAAgnQAAgmANgQQALgOATgBQAUABALAOQANAQAAAmQAAAngNARQgLAOgUAAQgTgBgMgPgAgIgsQgDADgCAIQgDAKAAAXQAAAYACAJQADAJAEADQADACAEAAQAFAAADgCQAEgDACgIQADgKAAgYQAAgXgDgJQgCgJgEgDQgDgDgFAAQgEAAgEADg");
	this.shape_2.setTransform(485.1,16.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#266CA1").s().p("AgtBEQACgNAHgNQAIgMAWgUQAQgQAEgGQAGgIAAgIQAAgIgFgFQgFgFgIAAQgHAAgFAFQgFAFAAAMIgagDQACgWAMgJQAMgJASAAQAUAAALALQAMAKAAARQAAAJgDAIQgEAIgHAIIgRASIgPAPIgFAHIAzAAIAAAYg");
	this.shape_3.setTransform(474.4,15.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAdBEIgUgeQgKgPgEgEQgEgFgEgBQgFgCgJAAIgGAAIAAA5IgbAAIAAiHIA5AAQAVAAALAEQAKADAFAKQAGAJAAAMQAAAPgJAKQgJAKgSACQAJAFAGAHQAGAFAKAQIAQAbgAghgJIAUAAQAUAAAEgCQAFgCADgEQADgEAAgGQAAgHgEgEQgDgEgHgBIgTgBIgWAAg");
	this.shape_4.setTransform(457.9,16);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgzBEIAAiHIBkAAIAAAXIhIAAIAAAeIBDAAIAAAWIhDAAIAAAlIBLAAIAAAXg");
	this.shape_5.setTransform(444.3,16);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgNBEIAAiHIAbAAIAACHg");
	this.shape_6.setTransform(435.1,16);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgOBEIgwiHIAdAAIAiBjIAhhjIAdAAIgwCHg");
	this.shape_7.setTransform(426.1,16);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAbBEIg2hYIAABYIgaAAIAAiHIAbAAIA3BaIAAhaIAZAAIAACHg");
	this.shape_8.setTransform(412.9,16);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAmBEIgMgfIg1AAIgLAfIgdAAIA1iHIAcAAIA2CHgAgSAOIAkAAIgSgxg");
	this.shape_9.setTransform(399.2,16);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AggA6QgKgLgBgWIAagDQABALADAFQAEAIAJAAQAJAAADgGQAEgFAAgQIAAhXIAcAAIAABVQAAARgDAJQgEAMgLAHQgKAHgRAAQgUAAgLgLg");
	this.shape_10.setTransform(386.5,16.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgeA6QgMgKgCgRIAZgDQABAJAGAGQAFAEAHAAQAHABAGgHQAGgFAAgLQAAgKgGgFQgFgHgIAAQgEAAgHACIADgUQAKAAAFgEQAGgFAAgIQAAgHgEgEQgEgEgGAAQgHAAgEAEQgFAFgBAJIgYgEQACgNAFgGQAFgIAKgEQAJgFALAAQASABAMALQAJAKAAANQAAASgTALQALACAHAIQAHAJAAAMQAAASgNAMQgNAOgTAAQgSAAgMgMg");
	this.shape_11.setTransform(371.2,16.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAEBEIAAhhQgNANgUAHIAAgYQAKgDAMgKQALgJAEgMIAWAAIAACHg");
	this.shape_12.setTransform(359.9,15.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#26B2E3").s().p("AATApQgHAFgHADQgGADgJAAQgTAAgJgLQgIgIAAgLQABgJAGgIQAFgHAMgFIgIgMQgDgGAAgEQAAgKAIgGQAHgGAOAAQALAAAHAGQAIAHAAAKQAAAGgDAFQgFAGgKAHIANARQADgEACgHIARAEIgFANIgDAHIAIAHIAIAFIgNAOQgIgEgHgHgAgWAMQgDAFAAAFQAAAGADAEQAFAEAGAAQAFAAAEgCQADgCAFgEIgTgYQgGADgDAFgAgMgjQgCACAAADQAAAEAEAFIAFAFIAFgEQAFgEAAgFQAAgDgCgDQgDgDgEAAQgFAAgDADg");
	this.shape_13.setTransform(350.6,17.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgtBEQACgNAHgNQAIgMAWgUQAQgQAEgGQAGgIAAgIQAAgIgFgFQgFgFgIAAQgHAAgFAFQgFAFAAAMIgagDQACgWAMgJQAMgJASAAQAUAAALALQAMAKAAARQAAAJgDAIQgEAIgHAIIgRASIgPAPIgFAHIAzAAIAAAYg");
	this.shape_14.setTransform(339.8,15.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AADBEIAAhhQgNANgTAHIAAgYQAKgDAMgKQALgJAFgMIAVAAIAACHg");
	this.shape_15.setTransform(328.7,15.9);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},154).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},40).wait(166));

	// foule
	this.instance_5 = new lib.foule("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(845.4,58.7,1,1,0,0,0,112.7,31.3);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(53).to({_off:false},0).to({x:615.4,y:59},35).wait(272));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_219 = new cjs.Graphics().p("EAqnACbIAAktIBqAAIAAEtg");
	var mask_1_graphics_220 = new cjs.Graphics().p("EAqPACbIAAktICaAAIAAEtg");
	var mask_1_graphics_221 = new cjs.Graphics().p("EAp2ACbIAAktIDMAAIAAEtg");
	var mask_1_graphics_222 = new cjs.Graphics().p("EApeACbIAAktID8AAIAAEtg");
	var mask_1_graphics_223 = new cjs.Graphics().p("EApGACbIAAktIEsAAIAAEtg");
	var mask_1_graphics_224 = new cjs.Graphics().p("EAouACbIAAktIFcAAIAAEtg");
	var mask_1_graphics_225 = new cjs.Graphics().p("EAoVACbIAAktIGOAAIAAEtg");
	var mask_1_graphics_226 = new cjs.Graphics().p("EAn9ACbIAAktIG+AAIAAEtg");
	var mask_1_graphics_227 = new cjs.Graphics().p("EAnlACbIAAktIHuAAIAAEtg");
	var mask_1_graphics_228 = new cjs.Graphics().p("EAnMACbIAAktIIgAAIAAEtg");
	var mask_1_graphics_229 = new cjs.Graphics().p("EAm0ACbIAAktIJQAAIAAEtg");
	var mask_1_graphics_230 = new cjs.Graphics().p("EAmcACbIAAktIKAAAIAAEtg");
	var mask_1_graphics_231 = new cjs.Graphics().p("EAmEACbIAAktIKwAAIAAEtg");
	var mask_1_graphics_232 = new cjs.Graphics().p("EAlrACbIAAktILiAAIAAEtg");
	var mask_1_graphics_233 = new cjs.Graphics().p("EAlTACbIAAktIMSAAIAAEtg");
	var mask_1_graphics_234 = new cjs.Graphics().p("EAk7ACbIAAktINCAAIAAEtg");
	var mask_1_graphics_235 = new cjs.Graphics().p("EAkiACbIAAktIN0AAIAAEtg");
	var mask_1_graphics_236 = new cjs.Graphics().p("EAkKACbIAAktIOkAAIAAEtg");
	var mask_1_graphics_237 = new cjs.Graphics().p("EAjyACbIAAktIPUAAIAAEtg");
	var mask_1_graphics_238 = new cjs.Graphics().p("EAjaACbIAAktIQEAAIAAEtg");
	var mask_1_graphics_239 = new cjs.Graphics().p("EAjBACbIAAktIQ2AAIAAEtg");
	var mask_1_graphics_240 = new cjs.Graphics().p("EAipACbIAAktIRmAAIAAEtg");
	var mask_1_graphics_241 = new cjs.Graphics().p("EAiRACbIAAktISWAAIAAEtg");
	var mask_1_graphics_242 = new cjs.Graphics().p("EAh4ACbIAAktITIAAIAAEtg");
	var mask_1_graphics_243 = new cjs.Graphics().p("EAhgACbIAAktIT4AAIAAEtg");
	var mask_1_graphics_244 = new cjs.Graphics().p("EAhIACbIAAktIUoAAIAAEtg");
	var mask_1_graphics_245 = new cjs.Graphics().p("EAgwACbIAAktIVYAAIAAEtg");
	var mask_1_graphics_246 = new cjs.Graphics().p("EAgXACbIAAktIWKAAIAAEtg");
	var mask_1_graphics_247 = new cjs.Graphics().p("Af/CbIAAktIW6AAIAAEtg");
	var mask_1_graphics_248 = new cjs.Graphics().p("AfnCbIAAktIXqAAIAAEtg");
	var mask_1_graphics_249 = new cjs.Graphics().p("AfPCbIAAktIYaAAIAAEtg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(219).to({graphics:mask_1_graphics_219,x:283.3,y:15.5}).wait(1).to({graphics:mask_1_graphics_220,x:285.7,y:15.5}).wait(1).to({graphics:mask_1_graphics_221,x:288.2,y:15.5}).wait(1).to({graphics:mask_1_graphics_222,x:290.6,y:15.5}).wait(1).to({graphics:mask_1_graphics_223,x:293,y:15.5}).wait(1).to({graphics:mask_1_graphics_224,x:295.4,y:15.5}).wait(1).to({graphics:mask_1_graphics_225,x:297.9,y:15.5}).wait(1).to({graphics:mask_1_graphics_226,x:300.3,y:15.5}).wait(1).to({graphics:mask_1_graphics_227,x:302.7,y:15.5}).wait(1).to({graphics:mask_1_graphics_228,x:305.2,y:15.5}).wait(1).to({graphics:mask_1_graphics_229,x:307.6,y:15.5}).wait(1).to({graphics:mask_1_graphics_230,x:310,y:15.5}).wait(1).to({graphics:mask_1_graphics_231,x:312.4,y:15.5}).wait(1).to({graphics:mask_1_graphics_232,x:314.9,y:15.5}).wait(1).to({graphics:mask_1_graphics_233,x:317.3,y:15.5}).wait(1).to({graphics:mask_1_graphics_234,x:319.7,y:15.5}).wait(1).to({graphics:mask_1_graphics_235,x:322.2,y:15.5}).wait(1).to({graphics:mask_1_graphics_236,x:324.6,y:15.5}).wait(1).to({graphics:mask_1_graphics_237,x:327,y:15.5}).wait(1).to({graphics:mask_1_graphics_238,x:329.4,y:15.5}).wait(1).to({graphics:mask_1_graphics_239,x:331.9,y:15.5}).wait(1).to({graphics:mask_1_graphics_240,x:334.3,y:15.5}).wait(1).to({graphics:mask_1_graphics_241,x:336.7,y:15.5}).wait(1).to({graphics:mask_1_graphics_242,x:339.2,y:15.5}).wait(1).to({graphics:mask_1_graphics_243,x:341.6,y:15.5}).wait(1).to({graphics:mask_1_graphics_244,x:344,y:15.5}).wait(1).to({graphics:mask_1_graphics_245,x:346.4,y:15.5}).wait(1).to({graphics:mask_1_graphics_246,x:348.9,y:15.5}).wait(1).to({graphics:mask_1_graphics_247,x:351.3,y:15.5}).wait(1).to({graphics:mask_1_graphics_248,x:353.7,y:15.5}).wait(1).to({graphics:mask_1_graphics_249,x:356.2,y:15.5}).wait(111));

	// 66
	this.instance_6 = new lib.lieu("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(639.5,18.3,1,1,0,0,0,72.9,12.6);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(219).to({_off:false},0).wait(30).to({startPosition:0},0).wait(111));

	// bouton
	this.instance_7 = new lib.bouton("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(388.6,103.5,1,1,0,0,0,47.5,10.2);
	this.instance_7._off = true;

	this.instance_8 = new lib.bouton_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(388.6,74.2,1,1,0,0,0,47.5,10.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_7}]},274).to({state:[{t:this.instance_8}]},25).wait(61));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(274).to({_off:false},0).to({_off:true,y:74.2,mode:"independent"},25,cjs.Ease.backOut).wait(61));

	// motif
	this.instance_9 = new lib.montagne("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(448.7,46.5,1,1,0,0,0,279.7,42.5);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},19).wait(341));

	// neige
	this.instance_10 = new lib.neige("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(372.2,-30.7,1,1,0,0,0,355.8,30.4);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(4).to({_off:false},0).to({x:370.7,y:31.3},295).wait(61));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(533,49,559.4,85);
// library properties:
lib.properties = {
	id: '7425AC61B635EF419D304F6A3D7451E7',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/_490772997.png?1515159384844", id:"_490772997"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['7425AC61B635EF419D304F6A3D7451E7'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;